2 - Method w/o timeout executed successfully.
2 - exception caught, this is expected.
2 - The exception was: CORBA.TIMEOUT(omniORB.TIMEOUT_CallTimedOutOnClient, CORBA.COMPLETED_MAYBE)
2 - Method w/o timeout executed successfully.
2 - Method w/o timeout executed successfully.
2 - exception caught, this is expected.
2 - The exception was: CORBA.TIMEOUT(omniORB.TIMEOUT_CallTimedOutOnClient, CORBA.COMPLETED_MAYBE)
2 - Method w/o timeout executed successfully.
2 - ----------T--:--:--.--- Python Client initialized by user@host disconnect - Disconnect called for client
2 - ----------T--:--:--.--- Python Client initialized by user@host disconnect - Disconnect called for client
