1 -  --endorsed -- alma.acs.testsupport.tat.NoDotJUnitRunner alma.acs.logging.AcsLoggerTest
1 - 
1 - ------------ testSimpleLog --------------
1 - <Debug TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testSimpleLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" LogId="0"><![CDATA[a really simple log]]></Debug>
1 - <Info TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testSimpleLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" LogId="1"><![CDATA[and quite informative]]></Info>
1 - 
1 - ------------ testAudienceLog --------------
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testAudienceLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="2" Audience="Operator"><![CDATA[Log with audience]]></Warning>
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testAudienceLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="3" Audience="Operator"><![CDATA[Log exception with audience]]><Data Name="LoggedException"><![CDATA[java.lang.Exception: My dummy exception
1 - 	at alma.acs.logging.AcsLoggerTest.testAudienceLog(AcsLoggerTest.java:33)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
1 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
1 - 	at java.lang.reflect.Method.invoke(Method.java:597)
1 - 	at junit.framework.TestCase.runTest(TestCase.java:154)
1 - 	at junit.framework.TestCase.runBare(TestCase.java:127)
1 - 	at junit.framework.TestResult$1.protect(TestResult.java:106)
1 - 	at junit.framework.TestResult.runProtected(TestResult.java:124)
1 - 	at junit.framework.TestResult.run(TestResult.java:109)
1 - 	at junit.framework.TestCase.run(TestCase.java:118)
1 - 	at junit.framework.TestSuite.runTest(TestSuite.java:208)
1 - 	at junit.framework.TestSuite.run(TestSuite.java:203)
1 - 	at junit.textui.TestRunner.doRun(TestRunner.java:116)
1 - 	at junit.textui.TestRunner.start(TestRunner.java:172)
1 - 	at alma.acs.testsupport.tat.NoDotJUnitRunner.main(NoDotJUnitRunner.java:41)
1 - ]]></Data></Warning>
1 - 
1 - ------------ testAntennaContextLog --------------
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testAntennaContextLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="4" Audience="Operator" Array="Array01" Antenna="Antenna01"><![CDATA[Log with audience, array and antenna]]></Warning>
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testAntennaContextLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="5" Array="Array01" Antenna="Antenna01"><![CDATA[Log with array and antenna]]></Warning>
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testAntennaContextLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="6" Audience="Operator" Array="Array01" Antenna="Antenna01"><![CDATA[Log exception with audience, array and antenna]]><Data Name="LoggedException"><![CDATA[java.lang.Exception: My dummy exception
1 - 	at alma.acs.logging.AcsLoggerTest.testAntennaContextLog(AcsLoggerTest.java:42)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
1 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
1 - 	at java.lang.reflect.Method.invoke(Method.java:597)
1 - 	at junit.framework.TestCase.runTest(TestCase.java:154)
1 - 	at junit.framework.TestCase.runBare(TestCase.java:127)
1 - 	at junit.framework.TestResult$1.protect(TestResult.java:106)
1 - 	at junit.framework.TestResult.runProtected(TestResult.java:124)
1 - 	at junit.framework.TestResult.run(TestResult.java:109)
1 - 	at junit.framework.TestCase.run(TestCase.java:118)
1 - 	at junit.framework.TestSuite.runTest(TestSuite.java:208)
1 - 	at junit.framework.TestSuite.run(TestSuite.java:203)
1 - 	at junit.textui.TestRunner.doRun(TestRunner.java:116)
1 - 	at junit.textui.TestRunner.start(TestRunner.java:172)
1 - 	at alma.acs.testsupport.tat.NoDotJUnitRunner.main(NoDotJUnitRunner.java:41)
1 - ]]></Data></Warning>
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testAntennaContextLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="7" Array="Array01" Antenna="Antenna01"><![CDATA[Log exception with array and antenna]]><Data Name="LoggedException"><![CDATA[java.lang.Exception: My dummy exception
1 - 	at alma.acs.logging.AcsLoggerTest.testAntennaContextLog(AcsLoggerTest.java:46)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
1 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
1 - 	at java.lang.reflect.Method.invoke(Method.java:597)
1 - 	at junit.framework.TestCase.runTest(TestCase.java:154)
1 - 	at junit.framework.TestCase.runBare(TestCase.java:127)
1 - 	at junit.framework.TestResult$1.protect(TestResult.java:106)
1 - 	at junit.framework.TestResult.runProtected(TestResult.java:124)
1 - 	at junit.framework.TestResult.run(TestResult.java:109)
1 - 	at junit.framework.TestCase.run(TestCase.java:118)
1 - 	at junit.framework.TestSuite.runTest(TestSuite.java:208)
1 - 	at junit.framework.TestSuite.run(TestSuite.java:203)
1 - 	at junit.textui.TestRunner.doRun(TestRunner.java:116)
1 - 	at junit.textui.TestRunner.start(TestRunner.java:172)
1 - 	at alma.acs.testsupport.tat.NoDotJUnitRunner.main(NoDotJUnitRunner.java:41)
1 - ]]></Data></Warning>
1 - 
1 - ------------ testArrayContextLog --------------
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testArrayContextLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="8" Audience="Operator" Array="Array01"><![CDATA[Log with audience and array]]></Warning>
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testArrayContextLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="9" Array="Array01"><![CDATA[Log with array]]></Warning>
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testArrayContextLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="10" Audience="Operator" Array="Array01"><![CDATA[Log exception with audience and array]]><Data Name="LoggedException"><![CDATA[java.lang.Exception: My dummy exception
1 - 	at alma.acs.logging.AcsLoggerTest.testArrayContextLog(AcsLoggerTest.java:53)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
1 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
1 - 	at java.lang.reflect.Method.invoke(Method.java:597)
1 - 	at junit.framework.TestCase.runTest(TestCase.java:154)
1 - 	at junit.framework.TestCase.runBare(TestCase.java:127)
1 - 	at junit.framework.TestResult$1.protect(TestResult.java:106)
1 - 	at junit.framework.TestResult.runProtected(TestResult.java:124)
1 - 	at junit.framework.TestResult.run(TestResult.java:109)
1 - 	at junit.framework.TestCase.run(TestCase.java:118)
1 - 	at junit.framework.TestSuite.runTest(TestSuite.java:208)
1 - 	at junit.framework.TestSuite.run(TestSuite.java:203)
1 - 	at junit.textui.TestRunner.doRun(TestRunner.java:116)
1 - 	at junit.textui.TestRunner.start(TestRunner.java:172)
1 - 	at alma.acs.testsupport.tat.NoDotJUnitRunner.main(NoDotJUnitRunner.java:41)
1 - ]]></Data></Warning>
1 - <Warning TimeStamp="xxx" File="alma.acs.logging.AcsLoggerTest"  Line="xxx" Routine="testArrayContextLog" Host="xxx" Process="alma.acs.logging.AcsLoggerTest" SourceObject="alma.acs.logging.AcsLoggerTest" Thread="main" StackId="unknown" StackLevel="0" LogId="11" Array="Array01"><![CDATA[Log exception with array]]><Data Name="LoggedException"><![CDATA[java.lang.Exception: My dummy exception
1 - 	at alma.acs.logging.AcsLoggerTest.testArrayContextLog(AcsLoggerTest.java:57)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
1 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
1 - 	at java.lang.reflect.Method.invoke(Method.java:597)
1 - 	at junit.framework.TestCase.runTest(TestCase.java:154)
1 - 	at junit.framework.TestCase.runBare(TestCase.java:127)
1 - 	at junit.framework.TestResult$1.protect(TestResult.java:106)
1 - 	at junit.framework.TestResult.runProtected(TestResult.java:124)
1 - 	at junit.framework.TestResult.run(TestResult.java:109)
1 - 	at junit.framework.TestCase.run(TestCase.java:118)
1 - 	at junit.framework.TestSuite.runTest(TestSuite.java:208)
1 - 	at junit.framework.TestSuite.run(TestSuite.java:203)
1 - 	at junit.textui.TestRunner.doRun(TestRunner.java:116)
1 - 	at junit.textui.TestRunner.start(TestRunner.java:172)
1 - 	at alma.acs.testsupport.tat.NoDotJUnitRunner.main(NoDotJUnitRunner.java:41)
1 - ]]></Data></Warning>
1 - 
1 - ------------ testWrapJdkLogger --------------
1 - Logger configuration error: no log level found for logger myJdkLoggerwrapper or its ancestors. Will use Level.ALL instead.
1 - --iso_time-- INFO [myJdkLoggerwrapper] A message logged by the AcsLogger that wraps the jdkLogger
1 - 
1 - 
1 - OK (5 tests)
1 - 
